### ISSUE TITLE
Shape of tile grid

### ISSUE THREAD

**Issue by bentref** [FelixMo42/hex_game#1]
Grid shape drawn by for loops is currently a parallelogram, is this what we want? If we want it to fit perfectly in the window, we can use axial coordinates to draw it rectangular. 

Bur more likely, we want the map to be much larger than the window, and scroll around as the user moves to other parts. Therefore, the shape can be anything. I'm partial to making it a big hexagon because that is the shape of the tiles.

**Comment by FelixMo42** [comment]
I think you're right. We should have an arbitrarily large map, and only load the parts we need at the moment.

We could have something like this:

```
class Hex :
    ... types of hex, colors, idk

class Map :
    hexs = a hash map with loaded hexs
    def get_hex(cord) :
         if we have hex return it,
         else loaded from file or something.
         It also lets us hide the implementation so that we can just return a dummy hex for testing portions
```

**Comment by bentref** [comment]
Definitely, I'll create these classes. I assume they should go in src/hexs.py? or should we create a separate file for dealing with the map?

**Comment by FelixMo42** [comment]
I think we should split the drawing stuff into something like hexdraw.py, and put each class in its own file. Keep the logic and drawing stuff separate.

**Comment by bentref** [comment]
> Keep the logic and drawing stuff separate.

Agreed. We do have the file `hexs.py` right now, which will be confusing if we also have a `hex.py` class for the logic and attributes of hex tiles. hexs.py seems to deal more on the drawing side of things, should we rename it to `hexdraw.py`?

**Comment by bentref** [comment]
alternatively, we could make the drawing stuff part of `polydraw.py`. Which do you think is better?

**Comment by FelixMo42** [comment]
The confusing name is a good point. I prefer files on the smaller side, so I would vote `hexdraw.py` over just putting it in `polydraw.py`.

**Comment by bentref** [comment]
I've pushed some files (to another branch) with the classes added. none of it actually does anything yet but it's scaffolding

**Comment by FelixMo42** [comment]
Why to a different branch?

**Comment by bentref** [comment]
Good question, I guess because it's work in progress. The game will run, though, so I guess I'll do a pull request
