### ISSUE TITLE
Is it hexes, or hexs?

### ISSUE THREAD

**Issue by FelixMo42** [FelixMo42/hex_game#11]
???

**Comment by bentref** [comment]
the correct plural spelling would be hexes, but I've been trying to stick to whatever conventions exist in our code.

**Comment by FelixMo42** [comment]
I think were using both right now, so idk

**Comment by bentref** [comment]
I'd go with hexes since that is the correct spelling, I think it would be good to standardize. I'll do a find-and-replace across all files at some point soon when other changes aren't happening
