### ISSUE TITLE
Create and manage player / entities in general

### ISSUE THREAD

**Issue by FelixMo42** [FelixMo42/hex_game#2]
How should we keep track of the players and outer entities in the world?

I think for now we can simply add a `player` field to the `Map` class and create a `Player` class.

The `Player` class probably only need a tile cord for now, but will definitely need more latter.

**Comment by bentref** [comment]
Yes, that sounds good, I'll add that to the list of classes I'm creating. I could see `player` having a lot more than just location coords, probably also health stats, score, etc.

**Comment by bentref** [comment]
I've also created an NPC class that will have an `interact_with(player)` method

In the Hex class, each Hex also has an attribute for occupant--that could be the player or an NPC, or perhaps even an object.

**Comment by FelixMo42** [comment]
I noticed that right now your storing the entities in the hexs them selves. I think it would be to store them in their own array.

**Comment by bentref** [comment]
Agreed. I'll do that in Map, so that the map has a coordinates map of hexes, and a coordinates map of entities.

**Comment by FelixMo42** [comment]
Is this done?

**Comment by bentref** [comment]
I'd say it is *probably done*, closing and moving to there :)
