### ISSUE TITLE
Load/save of state

### ISSUE THREAD

**Issue by bentref** [FelixMo42/hex_game#5]
How do we want to load and save the state of gameplay between plays? The simplest is probably same approach as in BYOW: replay strings. However, I wonder if that's inefficient/slow given the greater interactivity of this game

We could look into serializing Python objects, which would probably be the most foolproof if implemented correctly. It seems like it would be a lot of work to manually save every aspect of the state

**Comment by FelixMo42** [comment]
I think that we should save the data rather than the replay string. Seems like that would give us more flexibility and the ability to only load the parts we want to load.

**Comment by bentref** [comment]
I'll self-assign this and start implementing serialization, it seems it's done through Pickle and is fairly similar to the Java serialization we used for gitlet

**Comment by bentref** [comment]
Serialization works by saving the map to the `mapsave` file, this should preserve the whole game state and is working currently
